### ISSUE TITLE
installing p2data

### ISSUE THREAD

**Issue by sevdarafatov** [kharchenkolab/p2data#1]
First of all thank you for this package. Im trying to use package Pagoda2 for that purpose Im trying to install package p2data with "install.packages('p2data',` repos='https://kharchenkolab.github.io/drat/', type='source')"

The error message I got is:
package ‘p2data’ is not available for this version of R

A version of this package for your version of R might be available elsewhere,
see the ideas at
https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packages

install.packages('p2data', repos='https://kharchenkolab.github.io/drat/', type='source`)

The thing is I cannot change the R version of my env because of other dependencies. My question is: Is there any other way to install p2data ?

Thank you

**Comment by evanbiederstedt** [comment]
Hi @sevdarafatov 

You should be able to do this installation manually via GitHub as well. Clone the package, and then run `R CMD build .` and `R CMD INSTALL *gz`

i.e. 
```
git clone https://github.com/kharchenkolab/p2data.git
cd p2data
R CMD build .
R CMD INSTALL *gz
```

That should work. Best, Evan
